export enum TYPES {
  GET_USER_REPOS_LIST = "GET_USER_REPOS_LIST",
  GET_USER_REPOS_LIST_SUCCESS = "GET_USER_REPOS_LIST_SUCCESS",
  GET_USER_REPOS_LIST_ERROR = "GET_USER_REPOS_LIST_ERROR",
  SET_REPOS_SEARCH_BY_NAME = "SET_REPOS_SEARCH_BY_NAME",
  RESET_STATE = "RESET_STATE",
}
